version: '3.7'
services:


    postgres:
        container_name: postgres
        image: postgres:12
        restart: always
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=sesamunlock
            - POSTGRES_DB=module_e8
        ports:
            - "5432:5432"


    redis:
        container_name: redis
        image: redis:5.0.7
        ports:
            - "6379:6379"


    flask:
        build: ./backend
        container_name: flask
        restart: always
        command: gunicorn -w 4 -b 0.0.0.0:5000 app:app
        ports:
            - "5000:5000"
        environment:
            - DATABASE_URL=postgresql://postgres:sesamunlock@postgres:5432/module_e8
        depends_on:
            - postgres
            - redis
        entrypoint: ["./boot.sh"]


    celery:
        build: ./backend
        container_name: celery
        environment:
            - DATABASE_URL=postgresql://postgres:sesamunlock@postgres:5432/module_e8
            - CELERY_BROKER_URL=redis://redis:6379/0
            - CELERY_RESULT_BACKEND=redis://redis:6379/0
        depends_on:
            - redis
            - postgres
            - flask
        entrypoint:  ["./celery.sh"]


#    nginx:
#        build: ./nginx
#        container_name: nginx
#        restart: always
#        ports:
#            - "8000:8000"
